version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spot
      POSTGRES_PASSWORD: spot
      POSTGRES_DB: spot
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spotproxy

  spot-server:
    image: nlesc/spot-server:latest
    build:
      context: ./Docker
      dockerfile: Dockerfile
    container_name: spot-server
    hostname: spot-server   
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: ["/spot/wait-for-postgres.sh", "db", "--", "bash", "/spot/docker_init.sh"]
    environment:
      POSTGRES_USER: spot
      POSTGRES_PASSWORD: spot
      POSTGRES_DB: spot
    volumes:
      - spotserver:/spot
      - ./data:/data
    restart: always
    networks:
      - spotproxy    

networks:
  spotproxy:
    name: spotproxy
    driver: bridge

volumes:
  postgres:
    name: postgres
    driver: local
  spotserver:
    name: spotserver
    driver: local    